# -*- coding: utf-8 -*-
"""Internship_Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PlNo7nrrBdPCPnE4CW1eTNHt1KoIVitA

Our (hypothetical) marketing department needs some help in focussing on the most important market segment. Instead of marketing to everyone, they need our help in identifying who our most profitable customers are. Are they married or unmarried, working or retired, premium or budget buyers etc… This will help them position things better.

Also, they need help in identifying the bestselling products.

So, given the transaction data, help us identify the top 3 most profitable products and characteristics of our most loyal customers.  Also include your hypothesis of why you think the loyal customers like'''

#Importing libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import requests

"""##Loading the data from the drive
First we're going to create the folder and csv files to store the data which we're going to download from the drive link.
"""

data_dir = Path("./data")
purchase_data = data_dir/"purchase_behaviour.csv"
transaction_data = data_dir/"transaction_data.csv"

if data_dir.is_dir():
  print(f"{data_dir} Folder already exist!!!!!")
else:
  print(f"Creating the folder {data_dir}...........")
  Path.mkdir(data_dir)
  print(f"Created The folder {data_dir}!!!!!")

"""Now we're going build a function which will read the content of the drive link and the write the content to desire file location."""

def load_data(file_id:str, file: Path)->pd.DataFrame:

  """
  This function is used to load in the data from the give gogle drive file_id and saves the into the target file and returns the dataframe.
  **args:
      file_id: This takes in the url from where the data should be loaded from.
      file: This takes in the folder path where the data should be saved.
  """
  with open(file,"wb") as f1:
    response = requests.get(f"https://drive.google.com/uc?export=download&id={file_id}")
    f1.write(response.content)
  return pd.read_csv(file)

purchase_df = load_data("1Ha7uOqWOJcFUbZVT6C_JS40QlIneLbbd",purchase_data)
transaction_df = load_data("1w6QsVhoMO6VO8Kt_5SeZfIm1WHhqF7QW",transaction_data)
purchase_df.head()

transaction_df.head()

"""##Exploring the data

"""

purchase_df.info()

transaction_df.info()

purchase_df.describe()

transaction_df.describe().T

purchase_df.columns

transaction_df.columns

"""##Top 3 best selling product
We're going to use the group by method to group the best selling product on the from the product sales with the Total sales.
"""

top_products = transaction_df.groupby("PROD_NAME")["TOT_SALES"].sum().reset_index()

top_products = top_products.sort_values(by="TOT_SALES")

top_products.tail()

"""##Creating datafram of loyal customers
We're going to group the loyal custmers using the groupby fucntion to group the transactin id with the card number.
"""

purchase_df["PREMIUM_CUSTOMER"].value_counts(), purchase_df["LIFESTAGE"].value_counts()

loyal_customers = transaction_df.groupby("LYLTY_CARD_NBR")["TXN_ID"].count().reset_index().sort_values(by="TXN_ID",ascending=False)

loyal_customers.head()

"""##Creating the customer segmentation dataframe
We're going to now use the knowledge of the loyal customer and purchases data to get the details about our loyal customers.
"""

customer_segments = loyal_customers.merge(purchase_df, on="LYLTY_CARD_NBR", how="left")
customer_segments.head()

customer_segments.groupby(["LIFESTAGE", "PREMIUM_CUSTOMER"])["TXN_ID"].sum().reset_index()

customer_product_analysis = transaction_df.merge(purchase_df, on="LYLTY_CARD_NBR", how="left")
segment_product_sales = customer_product_analysis.groupby(["LIFESTAGE", "PREMIUM_CUSTOMER", "PROD_NAME"])["TOT_SALES"].sum().reset_index()
top_products_by_segment = segment_product_sales.sort_values(by="TOT_SALES", ascending=False).groupby(["LIFESTAGE", "PREMIUM_CUSTOMER"])
top_products_by_segment.head(10)

"""##Creating function to plot graph and showcase results"""

def plot_graph(data:pd.DataFrame):
  """This function is used to make barplot to know the relationship between the totla sales by product_name/lifestage/primum_cistomer.
  **args:
        data: This parameters takes in the pandas DataFrame object through which the data will be taken from for plotting.
  """

  # Set up the figure and subplots
  fig, axes = plt.subplots(1, 3, figsize=(20, 5))  # 1 row, 3 columns

  # --- Plot 1: Sales vs Product Name ---
  sns.barplot(x="TOT_SALES", y="PROD_NAME", data=data[:20], palette="viridis", ax=axes[0])
  axes[0].set_title("Top 10 Best-Selling Products")
  axes[0].set_xlabel("Total Sales")
  axes[0].set_ylabel("Product Name")

  # --- Plot 2: Sales by Premium vs. Budget Customers ---
  sns.barplot(x="PREMIUM_CUSTOMER", y="TOT_SALES", data=data, palette="coolwarm", ax=axes[1])
  axes[1].set_title("Total Sales by Customer Type")
  axes[1].set_xlabel("Customer Type")
  axes[1].set_ylabel("Total Sales")

  # --- Plot 3: Sales by Lifestage ---
  sns.barplot(x="TOT_SALES", y="LIFESTAGE", data=data, palette="magma", ax=axes[2])
  axes[2].set_title("Total Sales by Lifestage")
  axes[2].set_xlabel("Total Sales")
  axes[2].set_ylabel("Lifestage")

  # Adjust layout for better spacing
  plt.tight_layout()
  plt.show()

plot_graph(data=top_products_by_segment.head(2394))

"""#Hypothesis
##Why do loyal customers buy what they buy?

###1. Young Singles/Couples (Mainstream)

- Prefer Dorito Corn Chips Supreme 380g, Cheezels Cheese 330g, and Smiths Crinkle Chips Salt & Vinegar 330g.

- Hypothesis:
  - Likely prefer larger packs because they host gatherings, game nights, or casual snacking.

  - Mainstream customers may be looking for popular and well-known brands.

###2. Older Families (Budget)

- Buy Smiths Crinkle Chips Salt & Vinegar 330g and Dorito Corn Chips Supreme 380g.

- Hypothesis:
  - Larger families purchase bulk-sized packs for sharing.

  - Budget-conscious families may go for cheaper, high-value items.

###3. Retirees (Mainstream)

- Consistent buyers across multiple products.

- Hypothesis:
  - They have more stable shopping habits and prefer consistent quality over trends.

  - Likely purchase for personal consumption or family visits.

"""

